version: '3.7'

services:
  portainer:
    container_name: ${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}
    image: ${DOCKER_IMAGE_REGISTRY:-}${APP_PREFIX}/${SERVICE_NAME}:${APP_VERSION}
    restart: ${DOCKER_RESTART_POLICY}
    build:
      context: ./
      args:
        - DOCKER_BASE_IMAGE
    env_file:
      - ${DOCKER_GENERATED_ENV_FILE:-./env/defaults}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    ports:
      - ${PORTAINER_UI_PORT}
    networks:
      backend:
        aliases:
          - ${SERVICE_NAME}
      frontend:
        aliases:
          - ${SERVICE_NAME}
    logging:
      driver: ${DOCKER_LOGGING_DRIVER}
      options:
        max-file: ${DOCKER_LOGGING_MAX_FILE}
        max-size: ${DOCKER_LOGGING_MAX_SIZE}

networks:
  backend:
    name: ${APP_PREFIX}_${DOCKER_BACKEND_NETWORK_NAME}
    external: true
  frontend:
    name: ${DOCKER_FRONTEND_NETWORK_NAME}
    external: true

volumes:
  data:
    name: ${PORTAINER_VOLUME_NAME}
    driver: local
